name: ci-tests

on:
  workflow_dispatch:
  release:
    types: [released]
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install jq
        run: sudo apt install jq

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build container image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: tclscanner:latest

      - name: Test
        run: |
          docker run --rm -v $PWD/tests/tcl:/scandir tclscanner:latest \
            | jq | jq --sort-keys . \
            | diff --ignore-all-space --ignore-blank-lines - <(jq --sort-keys . tests/tcl.json)